#clear screen
alias cls='clear'

# Zoxide with FZF
alias ff='zi'

# Lazygit
alias lg='lazygit'

#rm with confirmation
#alias rm='rm -i'

#Apt-get update/upgrade#
#alias update='sudo apt-get update'
#alias upgrade='sudo apt-get upgrade'

#lsd aliases
alias ls='lsd -1'

alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'

#nvim
alias nv='nvim'

#VScode
alias cc='code $(fzf)'

#history
alias hh='history | fzf +s --tac'

#fzf

# Set up fzf key bindings and fuzzy completion (toimii ainoastaa versiossa 0.48.0 ja uudemmissa)
# eval "$(fzf --bash)"

#tmux
alias tmuxa='tmux attach'
