#clear screen
alias cls='clear'

# twt
alias chat='twt'
# lsd aliases
alias ls='lsd -1'
# alias ls='lsd'
alias l='ls -l'
# alias lla='ls -la'
alias lt='ls --tree'
alias ccls='cd && cls'
# alias ll='ls -alF'
alias ll='ls -lha'
alias la='ls -A'

# move up 1,2 or 3 directories
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'

# source .bashrc
alias sob='source ~/.bashrc'

# nvim
alias nv='nvim'

# fzf preview -> open with vscode
alias cc='code $(fzf -m --preview="batcat --color=always {}")'

# fzf preview -> open with nvim
alias nvf='nvim $(fzf -m --preview="batcat --color=always {}")'

# date
alias date='date "+%a %d/%m/%Y %H:%M:%S"'

#tmux
alias tmuxa='tmux attach'
alias tma='tmux attach'
alias tmls='tmux ls'
alias tmm='tmux new -s main'

#fzf with zoxide
alias ff='cdi'

# Lazygit
alias lg='lazygit'

# xsel
alias pbcopy='xsel --input --clipboard'
alias pbpaste='xsel --output --clipboard'

# Todo-cli
alias todol="todo list"
alias todod="todo done"
alias todou="todo undo"
alias todor="todo remove"
alias todoe="todo edit"
alias todoc="todo clear"
alias todoh="todo help"

